name: Release-plz

permissions: {}

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    release-plz-release:
        name: Release-plz release
        runs-on: ubuntu-latest
        container:
            image: archlinux:base-devel
        if: ${{ github.repository_owner == 'wayle-rs' }}
        permissions:
            pull-requests: write
            contents: write
        steps:
            - name: Install dependencies
              run: |
                  pacman --noconfirm --needed -Syu \
                    git \
                    rustup \
                    clang \
                    gtk4 \
                    libpulse \
                    fftw \
                    libpipewire \
                    systemd-libs

            - name: Setup Rust
              run: rustup default stable

            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
                  submodules: recursive

            - uses: release-plz/action@v0.5
              with:
                  command: release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    release-plz-pr:
        name: Release-plz PR
        runs-on: ubuntu-latest
        container:
            image: archlinux:base-devel
        if: ${{ github.repository_owner == 'wayle-rs' }}
        permissions:
            pull-requests: write
            contents: write
        concurrency:
            group: release-plz-${{ github.ref }}
            cancel-in-progress: false
        steps:
            - name: Install dependencies
              run: |
                  pacman --noconfirm --needed -Syu \
                    git \
                    rustup \
                    clang \
                    gtk4 \
                    libpulse \
                    fftw \
                    libpipewire \
                    systemd-libs

            - name: Setup Rust
              run: rustup default stable

            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
                  submodules: recursive

            - uses: release-plz/action@v0.5
              with:
                  command: release-pr
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
